Section favorite
teti-ruzh/news-js-team-project pull request #15
Opened 2023-03-24 00:22 UTC by yarikgorpl

Потрібно змінити назву файлу FavoUrite.html ,щоб співпадала з макетом

2023-03-24 07:52 UTC, LiudmylaKozytska requested changes
delete files index.css and index.css.map in sass folder

2023-03-25 17:58 UTC, teti-ruzh commented on .prettierrc
прибрати зміни в прітіер

2023-03-25 18:01 UTC, teti-ruzh requested changes
прибрати зміни в прітіер, зняти пуш міксін і veriables

2023-03-25 18:13 UTC, teti-ruzh approved these changes

2023-03-25 18:31 UTC, teti-ruzh approved these changes

2023-03-25 18:50 UTC, LiudmylaKozytska approved these changes

2023-03-25 18:50 UTC, merged